### ISSUE TITLE
DOCS: Outdated instruction

### ISSUE THREAD

**Issue by KOOKIIEStudios** [SoulGirlJP/AzureV316#13]
## Summary:
Request for setup guide update.

## Details
So I used to be the maintainer for the Wiki, but have since have had my permissions revoked *without notice*.
In any case, I'd just point out that [Step 6 of the setup guide I wrote](https://github.com/SoulGirlJP/AzureV316/wiki/Setup#6-configure-project-settings) is now outdated following the project's migration to Maven (courtesy of [Brandon](https://github.com/Bratah123) and [Desc](https://github.com/Descended)).
This is also true of the project structure [configuration screenshots I collated](https://github.com/SoulGirlJP/AzureV316/wiki/IntelliJ-Project-Structure).

## Remedy
I'd made new screenshots only to realise that my permissions have been revoked and I can no longer edit the wiki.
So here they are, in case some other maintainer (who still has access) wishes to perform the updates:

  - Instruction - Import Maven build script:
![import maven](https://i.imgur.com/a6j9jqq.png)  
Link: https://i.imgur.com/a6j9jqq.png  
  - Configuration (dependencies):
![dependencies](https://i.imgur.com/B3evSFU.png)
Link: https://i.imgur.com/B3evSFU.png

**Comment by Hatzilu** [comment]
Thank you!

**Comment by Bratah123** [comment]
Deprecated project, consider closing this issue?

**Comment by KOOKIIEStudios** [comment]
Probably not
The details outlined in this Wiki is still valid for the Azure forks

**Comment by Bratah123** [comment]
> Probably not
> The details outlined in this Wiki is still valid for the Azure forks

SGTM!
@SoulGirlJP What do you think? it might be good to update the docs here, as it seemed to have help some people out!
lmk wyt!

**Comment by Descended** [comment]
Hi @SoulGirlJP u closed this but the issue hasn't been fixed. Please state reasoning for close.
