### ISSUE TITLE
can't download AzureV316 Client.

### ISSUE THREAD

**Issue by Medeia-Beliar** [SoulGirlJP/AzureV316#14]
i tried client download.
but google drive link is broken.
pls fix it

**Comment by KOOKIIEStudios** [comment]
Soul classed this as a deprecated project so idk if he's still gonna refresh the links

**Comment by KOOKIIEStudios** [comment]
@Bratah123 @Descended do yall happen to have a copy of the client in the cloud?

**Comment by Bratah123** [comment]
Unfortunately no client download from me. @SoulGirlJP do you possibly still ahve a client download?

**Comment by feixria** [comment]
Was wondering if SoulGirlJP is active and is still willing to upload the client?

**Comment by SoulGirlJP** [comment]
@feixria @Medeia-Beliar i will upload right now! :)

**Comment by feixria** [comment]
Im not that knowledgeable. But, the setting up guide should at least make it so that I can setup the a server on localhost? Thanks alot for the troubles, @SoulGirlJP

**Comment by SoulGirlJP** [comment]
The current setup is made for hosting it for your own computer 127.0.0.1, you can always message me in discord SoulGirlJP#7859 if you have any questions regarding the setup guide or in general development questions regarding the maple private server scene <3

**Comment by Bratah123** [comment]
[Client](https://github.com/SoulGirlJP/AzureV316/wiki/Setup) has been uploaded as of 8/09/2021.
Flag for closing?
> The current setup is made for hosting it for your own computer 127.0.0.1

On side note, I have a client that opens up the server to other players (connecting with another ip). This issue is out of the scope of that, but lmk if it's a thing that should be added!

**Comment by feixria** [comment]
@Bratah123 Is it able to let others on the same LAN join?

**Comment by Bratah123** [comment]
@feixria Yes so long as the necessary ports are open for it of course

**Comment by feixria** [comment]
@Bratah123 If so, how do I get it?

**Comment by SoulGirlJP** [comment]
The client link has been updated in the setup guide page, and everything should be good now! I will now close this issue <3

**Comment by KOOKIIEStudios** [comment]
> @Bratah123 If so, how do I get it? 

You can contact him on Discord `Not Brandon#4444` to discuss custom client (and/or pricing)
